### ISSUE TITLE
Variable doc via in-line comment?

### ISSUE THREAD

**Issue by docnux** [NaturalDocs/NaturalDocs#20]
(I do not fully understand issue #13 - my request may overlap.)

Hello,

presently, information concerning variables must be put in a leading documentation block. What about the following?
Let NaturalDocs parse variable declaration lines and put them into the documentation output if they contain an in-line comment starting with "Variable:"?

Examples for Perl:

Code example 1:
my $foo; # Variable: Stores the foo state of the process

Doc result example 1:
Variable **foo**: Stores the foo state of the process

Code example 2 (not sure if necessary):
my $foo=10; # Variable: Stores the foo state of the process

Doc result example 2:
Variable **foo**: Starting value '10'. Stores the foo state of the process

**Comment by NaturalDocs** [comment]
I would only be able to do something like that for languages with [full support](http://www.naturaldocs.org/reference/language_support/).  Natural Docs can work with any language from just [a config file](http://www.naturaldocs.org/reference/languages.txt/) because the comment itself tells you what the code element is, and then there's only [very limited parsing](http://www.naturaldocs.org/reference/languages.txt/#adding_prototypes) needed afterwards to collect a prototype.  This wouldn't work with that system, and although a second system could be built around this idea, it's a bigger lift than you would think for just a small convenience.

For languages that do have full support I've thought about introducing something like this for enum values, but that would only affect those few languages and Perl isn't one of them at the moment.

**Comment by docnux** [comment]
Meanwhile I wrote a preprocessor in Perl which takes my standard comments and creates a temporary file which I then pass to NaturalDocs.
Thanks for NaturalDocs ... It's a great tool!
