### ISSUE TITLE
Source folder cannot be used

### ISSUE THREAD

**Issue by MegaManny** [NaturalDocs/NaturalDocs#37]
I have this error when I try to use make document. The soure file is a single C file (main.c) with simple code. I am following the getting started on the NaturalDocs Website.
The Project File has the following content.
`Source Folder: test

# ERROR: The source folder C:\Users\pcpc\Desktop\testProj\test wouldn't be used because it matches a filter, output folder, or configuration folder.`

**Comment by NaturalDocs** [comment]
Correct.  The source folder, output folder, and configuration folders must all be different and not subfolders of each other.  If that's not what you're doing and you think this error message is wrong, please attach Project.txt from your configuration folder and I'll look at it.

**Comment by NaturalDocs** [comment]
Actually, the output and project folders can probably be subfolders of the source folder, but they can't be the same folder.

**Comment by MegaManny** [comment]
[Project.txt](https://github.com/NaturalDocs/NaturalDocs/files/3400489/Project.txt)

**Comment by NaturalDocs** [comment]
So inbthat Project.txt it looks like you're using C:\My Project as the Natural Docs config folder and then using C:\My Project\Source and C:\My Project\Documentation for their respective folders.  The Natural Docs config folder should be its own subfolder, such as C:\My Project\ND Config.  At that point it will work.

Natural Docs excludes its config and documentation folders from its source file search, so if the source folder is a subfolder of the config folder, it won't be searched.  That's why it gives you this error message, so you know that the folder is getting excluded instead of just silently ignoring it.

**Comment by MegaManny** [comment]
Thank you for your support. Moving the config files to a separate subfolder made it work.
