### ISSUE TITLE
The first line in configuration file Project.txt must be the Format line.

### ISSUE THREAD

**Issue by dotherightthing** [NaturalDocs/NaturalDocs#38]
I'm setting up Natural Docs on MacOS for the first time and getting this error.

I've searched the Natural Docs site but I can't find any mention of what is expected here.

I took a wild stab and tried `Format: HTML` but that generated the error `The string "HTML" is not in a valid format for Version.`.

My `./config/Project.txt` is as follows. When I see the *Format* error, it is appended to the top of this file. 

```
Source Folder: ./
Ignore Source Folder: ./bin
Ignore Source Folder: ./docs
Ignore Source Folder: ./node_modules
Ignore Source Folder: ./vendor
HTML Output Folder: ./docs
Title: DTRT WordPress Plugin Boilerplate
Subtitle: Version 1.5.13

Copyright: Copyright (C) 2019 Dan Smith
```

I run this as follows:

```
mono /Applications/Natural\ Docs/NaturalDocs.exe ./config --pause-before-exit
```

OS: MacOS 10.14.6 (Mojave)
Mono: 6.0.0.319
Natural Docs: 2.0.2

**Comment by NaturalDocs** [comment]
Use "Format: 2.0" as the first line.  Also, paths are relative to the project file, so if this is config/Project.txt you should be using "../" instead of "./".

Tips to make it easier going forward: If you run NaturalDocs.exe ./config with the config folder empty it will generate empty templates for you to edit.  Also, you can put absolute paths in Project.txt and it will convert them to relative for you on the next run.

**Comment by dotherightthing** [comment]
@NaturalDocs Thanks, I did as you suggested and the documentation now generates fine on MacOS.

I have a couple of other questions. Should I ask them here, open a new issue, or use a different channel?
