### ISSUE TITLE
Hyperlink not working for other classes with fullname in C++

### ISSUE THREAD

**Issue by Neko-Box-Coder** [NaturalDocs/NaturalDocs#78]
When the full name of other classes are referenced from a class, the hyperlink to that class is not shown (occasionally).

So for example:

SomeClass.hpp
```
//namespace: SomeNamespace
namespace SomeNamespace
{
    //class: SomeClass
    class SomeClass
    {        
        public:
            //function: CreateOtherClass
            //This should reference <SomeNamespace.InnerNamespace.OtherClass>
            SomeNamespace::InnerNamespace::OtherClass CreateOtherClass();
    };
}
```

OtherClass.hpp
```
//namespace: SomeNamespace::InnerNamespace
namespace SomeNamespace::InnerNamespace
{
    //class: OtherClass
    class OtherClass
    {};
}
```

Here's the example in files: 
[TestNaturalDocs.zip](https://github.com/NaturalDocs/NaturalDocs/files/8602959/TestNaturalDocs.zip)

Natural Docs version: 2.1.1

**Comment by Neko-Box-Coder** [comment]
Just realized the comment for <SomeNamespace.InnerNamespace.OtherClass> should be <SomeNamespace::InnerNamespace::OtherClass>instead but I think it doesn't really matter too much as it is still the same result.

**Comment by NaturalDocs** [comment]
It shouldn't matter for links.  You can write <SomeNamespace.InnerNamespace.OtherClass> or <SomeNamespace::InnerNamespace::OtherClass> and it should work either way.

The issue is that you have to document your classes with the full namespace:

```
//namespace: SomeNamespace
namespace SomeNamespace
{
    //class: SomeNamespace::SomeClass
    class SomeClass
    {        
        public:
            //function: CreateOtherClass
            //This should reference <SomeNamespace.InnerNamespace.OtherClass>
            SomeNamespace::InnerNamespace::OtherClass CreateOtherClass();
    };
}
```

and

```
//namespace: SomeNamespace::InnerNamespace
namespace SomeNamespace::InnerNamespace
{
    //class: SomeNamespace::InnerNamespace::OtherClass
    class OtherClass
    {};
}
```

[Scope is explained here.](https://www.naturaldocs.org/reference/scope/)  Since C++ doesn't have full language support you have to go by the Comment Scope section.  Note the part on nested scopes.  Functions will inherit the class' scope automatically, but classes won't inherit the namespaces.  On the plus side, you can skip commenting the namespaces if the only thing in them you're documenting are classes.

**Comment by Neko-Box-Coder** [comment]
Thanks for answering, that makes sense now. I can't test it out atm but will do later. 
I will close the issue after testing it out just to make sure I get what you are saying.
