### ISSUE TITLE
NaturalDocs on Mac M1 ARM64

### ISSUE THREAD

**Issue by zhew1118** [NaturalDocs/NaturalDocs#85]
Hi all,

There is an issue with running the NaturalDocs on Mac M1 ARM64:

`------------------------------------------------------------
Natural Docs has stopped because of the following error:

libNaturalDocs.Engine.SQLite.Mac64.so assembly:<unknown assembly> type:<unknown type> member:(null)
(System.DllNotFoundException)

A crash report has been generated at /Users/zhewang/Desktop/sdk/js-adm/build/tmp/config/Working Data/LastCrash.txt.
Please include this file when asking for help at naturaldocs.org.
------------------------------------------------------------

NaturalDocs -q -i src/interface/ -o FramedHTML build/doc/internal -p build/tmp/config

------------------------------------------------------------
Natural Docs has stopped because of the following error:

libNaturalDocs.Engine.SQLite.Mac64.so assembly:<unknown assembly> type:<unknown type> member:(null)
(System.DllNotFoundException)

A crash report has been generated at /Users/zhewang/Desktop/sdk/js-adm/build/tmp/config/Working Data/LastCrash.txt.
Please include this file when asking for help at naturaldocs.org.
------------------------------------------------------------`

**Comment by NaturalDocs** [comment]
Sorry for the delay, I didn't have access to a Mac.

Prior to this happening, did you get a warning from macOS which said "libNaturalDocs.Engine.SQLite.Mac64.so cannot be opened because the developer cannot be verified"?  If so, you need to go to System Preferences > Privacy & Security.  Then scroll down to the Security section where you'll see a notice "libNatural...e.Mac64.so was blocked from use because it is not from an identified developer."  Click Allow Anyway and try again.

**Comment by eminakgun** [comment]
It does not seem to be blocked in my case and still having the same error

**Comment by NaturalDocs** [comment]
Natural Docs 2.3 was released which includes the signed SQLite binaries so you shouldn't have to worry about security settings anymore, it should just work.  If 2.3 doesn't work for you please reopen this issue.
