### ISSUE TITLE
Language Specific Data Types

### ISSUE THREAD

**Issue by eminakgun** [NaturalDocs/NaturalDocs#88]
Even though types defined using `typedef` are added to the documentation as declaration code snippet but some of the language specific data types are not listed in the documentation as declaration snippet. Why is that? Language I'm using is SystemVerilog and is defined in Languages.txt.

For example,

```
// Variable: some_var
// Some documentation
bit some_var;
```
Only `Some documentation` part appears in the html output, not `bit some_var;`

I've tried editing Comments.txt as below, but did not solve the problem.

```
Alter Comment Type: Variable
    Flags: Code, Variable Type
    Keywords:
        bit
```

Whats interesting is, another data type e.g `time` works fine. What am I missing?

P.S Using 2.2 stable version from website

**Comment by NaturalDocs** [comment]
So the little code snippets are called prototypes, and they're governed by settings in Languages.txt as explained here:

https://www.naturaldocs.org/reference/languages.txt/#adding_prototypes

In your case you would want to add this line to Languages.txt under the SystemVerilog heading:

`Variable Prototype Ender: ;`

That should work for your example above.  You may need to add more for other code elements or other ways they can be defined.

**Comment by eminakgun** [comment]
`Variable Prototype Ender: ;` is already there, so adding `=` resolved the prototype problem but introduced new side effects.

Let's say there is a default value assignment for the variable,
```
bit some_var = 'b1;
some_type_t some_type = SOME_TYPE_VALUE;
```

Before adding `=` user defined data type in the second line did appear in the documentation as expected untli `;` as prototype. But `bit `data type in the first line fails to do so. 
After adding `=`, it prevented the whole default value assignments to disappear from the documentation while including the `bit `data type prototype until `=`.

**Comment by NaturalDocs** [comment]
For variables this is expected behavior.  Most languages have = as a variable prototype ender because you don't want to include the default value in the output.  If you did you can omit the = and only have ; as an ender.

For typedefs I imagine you would want the part after the = since that's the type definition instead of just a default value.  In that case you definitely would want to omit the = and only have ; as an ender so that it's included.  If typedefs and variables should be handled differently then you would want to add a separate typedef comment type and keywords in Comments.txt and have separate prototype enders lines for them in Languages.txt.

I'm not 100% sure I'm reading your comment correctly so let me know if I'm not understanding what you meant.

**Comment by eminakgun** [comment]
Thank's for the explanation, you elaborated well, I've got some insights for typedef specific comment types. But, according to my understanding, 

```
// Variable: some_var
// Some documentation
bit some_var = 0;
```

should appear in the output including the prototype once `Variable Prototype Ender: ;` is present in Languages.txt. However it does not, in my case.

What I wanted to highlight in the last comment is, when I add `=` next to` ; ` in Languages.txt so that it becomes,
>`Variable Prototype Ender: ; =`

and finally it appears in the output as,

>`bit some_var`

It looks like ND fails to recognize `;` for `some_var`.

**Comment by NaturalDocs** [comment]
It works for me both ways.  Are you able to e-mail me your Languages.txt, Comments.txt, and the source file you're having problems with?  My e-mail address is here: https://www.naturaldocs.org/support/

**Comment by NaturalDocs** [comment]
It's been a couple of months without a response so I'm closing this.  Please reopen if you still want to work on this.
