### ISSUE TITLE
Table support?

### ISSUE THREAD

**Issue by tysenmoore-xse** [NaturalDocs/NaturalDocs#93]
Is there a way to create tables within the documentation. More specifically inside the supporting "txt" files? I think I know the answer, no, but I thought there might be some workaround that I might not be aware of.

**Comment by NaturalDocs** [comment]
Not really.  The best you can do is a text-based table in a text block:
```
=== Table ===
+----------+----------+
| X        | Comment  |
+----------+----------+
| Y        | Comment  |
+----------+----------+
=============
```
You can use -, =, or _ to delineate the text block, but you should use whichever won't appear as a line inside the table.  You can also use (Start Table) and (End) instead of the newer syntax.
```
(start table)
+----------+----------+
| X        | Comment  |
+----------+----------+
| Y        | Comment  |
+----------+----------+
(end)
```
I know text tables are kind of a pain though.

**Comment by tysenmoore-xse** [comment]
Thanks for the fast response.
